on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"

name: 📦 Build
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]
        arch: ["x86", "x64"]

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 🧰 Build Dependencies
        run: "pacman --noconfirm -Syu cmake gcc git ninja mingw-w64"

      - name: 🔧 Compile
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-${{ matrix.arch }}.cmake
          cmake --build build --config Release

      - name: 📤 Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-${{ matrix.arch }}
          path: |
            build/*.dll
